# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

export PATH=$PATH:/c/hub-windows-amd64-2.2.3/bin

eval "$(hub alias -s)"
alias open=explorer

alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"

export EDITOR=$(which vim)


function __parse_git_branch { 
  # fastest way I'm aware of
  sed 's/ref: refs\/heads\///' 2>/dev/null <.git/HEAD | sed 's/.*/ &/'
}

function __git_is_dirty {
  git status --porcelain 2> /dev/null | tr '\n' ' ' | sed -e 's/.*/ */'
}

export PS1="\[\033]0;MINGW64:/c/Users/nolawson\007\]\[\033[32m\]\[\033[35m\]\[\033[33m\]\w\[\033[36m\]\$(__parse_git_branch)\[\033[0m\]\$(__git_is_dirty)\[\033[35m\] (>'.')> \[\033[0m\]"
